# Project
version=1.0.0
group=ua.eismont.deathechoes
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Death Echoes
mod_author=eismont
mod_id=deathechoes
license=MIT
credits=
description=Your deaths leave ghostly echoes behind - translucent replays of your final moments. Right-click your echo to reclaim lost XP.
minecraft_version_range=[1.21.11, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.141.6+1.21.11
fabric_loader_version=0.19.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.11.45
neoforge_version_range=[21.11, 22.0)
neoforge_loader_version_range=[4, )
